"""
nl_to_sql.py — Hybrid NL query orchestrator for PulseBoard.

v3.0: Hybrid routing added.
  1. EDA intent → run_eda() (local, no LLM)
  2. Rule engine (fast, deterministic)
  3. LLM fallback (Gemini) when rule engine confidence == 0

Public API (unchanged contract — main.py and frontend require no changes):
    nl_to_sql_with_retry(question, schema, executor, session_id?) -> dict
"""

from nl_engine import parse_nl_query
from services.llm_router import (
    detect_eda_intent,
    should_use_llm,
    call_llm_for_sql,
    call_llm_for_query_explanation,
)


def nl_to_sql_with_retry(
    question: str,
    schema: dict,
    executor,
    session_id: str = "default",
) -> dict:
    """
    Route a natural-language question to the best available engine:
      - EDA intent  → local EDA engine (handled upstream in main.py)
      - Rule engine → fast deterministic SQL
      - LLM fallback → Gemini 2.0 Flash when rules fail

    Returns:
        {
            sql, result, attempts, success,
            source: "rules" | "llm" | "eda",
            warning, error, fallback_message, example_queries,
            llm_explanation (optional)
        }
    """
    # ── Step 1: Parse NL → SQL via rule engine ────────────────────────────────
    parse_result = parse_nl_query(question, schema)

    # ── Step 2: Rule engine succeeded ────────────────────────────────────────
    if not parse_result["fallback"] and parse_result.get("sql"):
        sql = parse_result["sql"]
        try:
            result = executor(sql)
            return {
                "sql":            sql,
                "result":         result,
                "attempts":       1,
                "success":        True,
                "source":         "rules",
                "warning":        parse_result.get("warning"),
                "template_id":    parse_result.get("template_id"),
                "confidence":     parse_result.get("confidence"),
                "example_queries": parse_result.get("example_queries", []),
            }
        except Exception as exec_err:
            # SQL generated but execution failed — try LLM before giving up
            parse_result["fallback"] = True
            parse_result["confidence"] = 0.0
            parse_result["exec_error"] = str(exec_err)

    # ── Step 3: Rule engine failed — try LLM if available ────────────────────
    if should_use_llm(parse_result, question, schema):
        llm_result = call_llm_for_sql(question, schema, session_id=session_id)

        if llm_result["success"] and llm_result.get("sql"):
            sql = llm_result["sql"]
            try:
                result = executor(sql)
                return {
                    "sql":            sql,
                    "result":         result,
                    "attempts":       1,
                    "success":        True,
                    "source":         "llm",
                    "warning":        "Answer generated by AI — verify results.",
                    "example_queries": parse_result.get("example_queries", []),
                }
            except Exception:
                pass  # LLM SQL also failed — fall through to error

        # LLM couldn't produce SQL — return natural language explanation
        explanation = call_llm_for_query_explanation(question, schema, session_id=session_id)
        if explanation:
            return {
                "sql":             "",
                "result":          None,
                "attempts":        1,
                "success":         False,
                "source":          "llm",
                "llm_explanation": explanation,
                "error":           "Could not generate SQL — see AI explanation below.",
                "example_queries": parse_result.get("example_queries", []),
                "warning":         None,
            }

    # ── Step 4: Deterministic fallback — safe SELECT * ────────────────────────
    fallback_sql = "SELECT * FROM data LIMIT 10"
    try:
        result = executor(fallback_sql)
        return {
            "sql":            fallback_sql,
            "result":         result,
            "attempts":       1,
            "success":        True,
            "source":         "rules",
            "warning":        (
                parse_result.get("fallback_message") or
                "Couldn't understand query — showing first 10 rows instead."
            ),
            "example_queries": parse_result.get("example_queries", []),
        }
    except Exception:
        pass

    # ── Step 5: Complete failure ───────────────────────────────────────────────
    return {
        "sql":             "",
        "result":          None,
        "attempts":        1,
        "success":         False,
        "source":          "rules",
        "error":           parse_result.get("fallback_message") or "Query failed.",
        "fallback_message": parse_result.get("fallback_message"),
        "example_queries": parse_result.get("example_queries", []),
        "warning":         None,
    }
